name: Kingdom Hearts (Final Mix)
sha1: b62bf252fdaf0b1a726668e28c244e1d83bcb146
options:
  basename: SLPS_251.98
  target_path: SLPS_251.98.rom
  elf_path: build/fm/SLPS_251.98.elf
  base_path: ..

  platform: ps2
  compiler: EEGCC

  asm_path: asm
  src_path: src
  build_path: build/fm

  ld_script_path: SLPS_251.98.ld
  ld_dependencies: True
  ld_wildcard_sections: True
  ld_bss_contains_common: True

  create_asm_dependencies: True
  generate_asm_macros_files: False
  find_file_boundaries: False
  disasm_unknown: True
  named_regs_for_c_funcs: False
  mips_abi_gpr: numeric
  hasm_in_src_path: True
  subalign: 8
  gp_value: 0x494050

  symbol_addrs_path:
  - config/fm/symbol_addrs.txt
  - config/fm/lib_symbol_addrs.txt

  create_undefined_funcs_auto: True
  undefined_funcs_auto_path: config/fm/undefined_funcs_auto.txt
  create_undefined_syms_auto: True
  undefined_syms_auto_path: config/fm/undefined_syms_auto.txt

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  section_order: [ ".text", ".data", ".rodata", ".bss" ]
  auto_link_sections: [ ".data", ".rodata", ".bss" ]

segments:
- name: main
  type: code
  start: 0x0
  vram: 0x100000
  bss_size: 0x1e0f80
  subsegments:
  - [ 0x0, asm, crt0 ]
  - [ 0x1d8, asm ]
  - [ 0x12270, c, worldfile ]
  - [ 0x12498, asm ]

  - [ 0x14f318, asm, lib/libc/bsearch ]
  - [ 0x14f3e8, asm, lib/libc/exit ]
  - [ 0x14f498, asm, lib/libc/fiprintf ]
  - [ 0x14f4f0, asm, lib/libc/malloc ]
  - [ 0x14f590, asm, lib/libc/malloc_r ]
  - [ 0x14ff10, asm, lib/libc/memcmp ]
  # - [0x14FFA4, asm, lib/libc/memcpy]
  # - [0x150054, asm, lib/libc/memset]
  - [ 0x150118, asm, lib/libc/mloc ]
  - [ 0x1501e8, asm, lib/libc/printf ]
  - [ 0x1502b8, asm, lib/libc/puts ]
  - [ 0x150360, asm, lib/libc/qsort ]
  - [ 0x150d50, asm, lib/libc/rand ]
  - [ 0x150dd0, asm, lib/libc/sbrkr ]
  - [ 0x150e28, asm, lib/libc/sprintf ]
  - [ 0x150f40, asm, lib/libc/strcat ]
  # - [0x15106C, asm, lib/libc/strcmp]
  - [ 0x1511b0, asm, lib/libc/strcpy ]
  # - [0x1512C4, asm, lib/libc/strlen]
  - [ 0x151400, asm, lib/libc/strncmp ]
  - [ 0x1515b8, asm, lib/libc/vfiprintf ]
  - [ 0x152328, asm, lib/libc/vfprintf ]
  - [ 0x153db0, asm, lib/libc/vsprintf ]
  - [ 0x153e60, asm, lib/libc/wsetup ]
  - [ 0x153f70, asm, lib/libc/abort ]
  - [ 0x153f88, asm, lib/libc/dtoa ]
  - [ 0x155420, asm, lib/libc/fflush ]
  - [ 0x155538, asm, lib/libc/findfp ]
  - [ 0x1557d8, asm, lib/libc/freer ]
  - [ 0x155c40, asm, lib/libc/fvwrite ]
  - [ 0x156020, asm, lib/libc/fwalk ]
  - [ 0x1560b8, asm, lib/libc/locale ]
  - [ 0x1561a0, asm, lib/libc/makebuf ]
  - [ 0x1562f8, asm, lib/libc/mbtowc_r ]
  # - [0x15632C, asm, lib/libc/memchr]
  # - [0x15640C, asm, lib/libc/memmove]
  - [ 0x156510, asm, lib/libc/mprec ]
  - [ 0x157528, asm, lib/libc/s_isinf ]
  - [ 0x157570, asm, lib/libc/s_isnan ]
  - [ 0x1575b0, asm, lib/libc/signal ]
  - [ 0x157898, asm, lib/libc/signalr ]
  - [ 0x157910, asm, lib/libc/stdio ]
  - [ 0x157a80, asm, lib/libc/writer ]
  - [ 0x157ae0, asm, lib/libc/callocr ]
  - [ 0x157b98, asm, lib/libc/closer ]
  - [ 0x157bf0, asm, lib/libc/fstatr ]
  - [ 0x157c50, asm, lib/libc/lseekr ]
  - [ 0x157cb0, asm, lib/libc/readr ]

  # lib/libkernl #
  - [ 0x157d40, asm, lib/libkernl/klib ]
  - [ 0x1585e0, asm, lib/libkernl/glue ]
  - [ 0x1589b0, asm, lib/libkernl/cache ]
  - [ 0x158c30, asm, lib/libkernl/intr ]
  - [ 0x158e60, asm, lib/libkernl/tty ]
  - [ 0x159380, asm, lib/libkernl/kprintf ]
  - [ 0x159d20, asm, lib/libkernl/sifrpc ]
  - [ 0x15ac80, asm, lib/libkernl/filestub ]
  - [ 0x15e328, asm, lib/libkernl/eeloadfile ]
  - [ 0x15f088, asm, lib/libkernl/iopreset ]
  - [ 0x15f338, asm, lib/libkernl/diei ]
  - [ 0x15f398, asm, lib/libkernl/initsys ]
  - [ 0x15f600, asm, lib/libkernl/libosd ]
  - [ 0x15fa20, asm, lib/libkernl/alarm ]
  - [ 0x15fb60, asm, lib/libkernl/thread ]
  - [ 0x15fec0, asm, lib/libkernl/deci2 ]
  - [ 0x1600a0, asm, lib/libkernl/sifcmd ]
  - [ 0x1607e8, asm, lib/libkernl/tlbfunc ]
  - [ 0x160d00, asm, lib/libkernl/tlbtrap ]

  # lib/libgcc #
  - [ 0x161060, asm, lib/libgcc/_muldi3 ]
  - [ 0x1610d8, asm, lib/libgcc/_divdi3 ]
  - [ 0x161770, asm, lib/libgcc/_moddi3 ]
  - [ 0x161e00, asm, lib/libgcc/_udivdi3 ]
  - [ 0x162380, asm, lib/libgcc/_umoddi3 ]
  - [ 0x1628e8, asm, lib/libgcc/_fixunsdfdi ]
  - [ 0x162a00, asm, lib/libgcc/_fixunssfdi ]
  - [ 0x162b28, asm, lib/libgcc/main ]
  - [ 0x162cb0, asm, lib/libgcc/_sf_to_df ]
  - [ 0x162cf0, asm, lib/libgcc/_addsub_df ]
  - [ 0x163010, asm, lib/libgcc/_mul_df ]
  - [ 0x163298, asm, lib/libgcc/_div_df ]
  - [ 0x1633d8, asm, lib/libgcc/_compare_df ]
  - [ 0x163428, asm, lib/libgcc/_si_to_df ]
  - [ 0x1634e0, asm, lib/libgcc/_df_to_si ]
  - [ 0x163580, asm, lib/libgcc/_make_df ]
  - [ 0x1635b0, asm, lib/libgcc/_df_to_sf ]
  - [ 0x163608, asm, lib/libgcc/_df_to_usi ]
  - [ 0x1636a8, asm, lib/libgcc/frame-dwarf2 ]
  - [ 0x164c38, asm, lib/libgcc/_floatdidf ]
  - [ 0x164ce0, asm, lib/libgcc/_unpack_sf ]
  - [ 0x164d40, asm, lib/libgcc/_make_sf ]
  - [ 0x164d70, asm, lib/libgcc/_pack_df ]
  - [ 0x164e48, asm, lib/libgcc/_unpack_df ]
  - [ 0x164f08, asm, lib/libgcc/_fpcmp_parts_df ]
  - [ 0x165028, asm, lib/libgcc/_pack_sf ]
  - [ 0x1650e0, asm, lib/libgcc/atexit ]
  - [ 0x165180, asm, lib/libgcc/errno ]
  - [ 0x165190, asm, lib/libgcc/strncpy ]

  - [ 0x165350, asm, lib/libgraph ]
  - [ 0x166ab0, asm, lib/libdma ]
  - [ 0x1672f8, asm, lib/libvu0 ]
  - [ 0x168040, asm, lib/libdbc ]
  - [ 0x168aa0, asm, lib/libpad2 ]
  - [ 0x1692f8, asm, lib/libvib ]
  - [ 0x169468, asm, lib/libcdvd ]

  # lib/libm #
  - [ 0x16ad60, asm, lib/libm/s_atan ]
  - [ 0x16b228, asm, lib/libm/s_ceil ]
  - [ 0x16b438, asm, lib/libm/s_cos ]
  - [ 0x16b560, asm, lib/libm/s_fabs ]
  - [ 0x16b598, asm, lib/libm/s_nan ]
  - [ 0x16b5c0, asm, lib/libm/s_sin ]
  - [ 0x16b6f8, asm, lib/libm/sf_cos ]
  - [ 0x16b7d0, asm, lib/libm/sf_sin ]
  - [ 0x16b8b8, asm, lib/libm/sf_tan ]
  - [ 0x16b930, asm, lib/libm/w_asin ]
  - [ 0x16b948, asm, lib/libm/w_atan2 ]
  - [ 0x16b960, asm, lib/libm/w_sqrt ]
  - [ 0x16b978, asm, lib/libm/wf_acos ]
  - [ 0x16b990, asm, lib/libm/wf_asin ]
  - [ 0x16b9a8, asm, lib/libm/wf_atan2 ]
  - [ 0x16b9c0, asm, lib/libm/wf_fmod ]
  - [ 0x16b9d8, asm, lib/libm/wf_pow ]
  - [ 0x16b9f0, asm, lib/libm/wf_sqrt ]
  - [ 0x16ba08, asm, lib/libm/e_asin ]
  - [ 0x16c060, asm, lib/libm/e_atan2 ]
  - [ 0x16c3a0, asm, lib/libm/e_rem_pio2 ]
  - [ 0x16c958, asm, lib/libm/e_sqrt ]
  - [ 0x16cc78, asm, lib/libm/ef_acos ]
  - [ 0x16d0a0, asm, lib/libm/ef_asin ]
  - [ 0x16d440, asm, lib/libm/ef_atan2 ]
  - [ 0x16d620, asm, lib/libm/ef_fmod ]
  - [ 0x16d7f0, asm, lib/libm/ef_pow ]
  - [ 0x16dfd0, asm, lib/libm/ef_rem_pio2 ]
  - [ 0x16e380, asm, lib/libm/ef_sqrt ]
  - [ 0x16e450, asm, lib/libm/k_cos ]
  - [ 0x16e728, asm, lib/libm/k_rem_pio2 ]
  - [ 0x16f278, asm, lib/libm/k_sin ]
  - [ 0x16f4b0, asm, lib/libm/kf_cos ]
  - [ 0x16f600, asm, lib/libm/kf_rem_pio2 ]
  - [ 0x16fe68, asm, lib/libm/kf_sin ]
  - [ 0x16ff70, asm, lib/libm/kf_tan ]
  - [ 0x1701f8, asm, lib/libm/s_floor ]
  - [ 0x170410, asm, lib/libm/s_scalbn ]
  - [ 0x1705f8, asm, lib/libm/sf_atan ]
  - [ 0x170888, asm, lib/libm/sf_fabs ]
  - [ 0x1708b0, asm, lib/libm/sf_floor ]
  - [ 0x170988, asm, lib/libm/sf_scalbn ]
  - [ 0x170a50, asm, lib/libm/s_copysign ]
  - [ 0x170a98, asm, lib/libm/sf_copysign ]

  - [ 0x170ad8, asm, lib/libpc ]
  - [ 0x170b60, asm, lib/libmc ]
  - [ 0x1723c8, asm, lib/libipu/libipu ]
  - [ 0x172738, asm, lib/libipu/ipuinit ]

  ## .data section ##
  - [ 0x172c70, data ]
  - [ 0x1bcc28, .data, worldfile ]
  - [ 0x1bcda0, data ]
  - [ 0x36ae28, data, lib/libc/mlock ]
  - [ 0x36ae30, data, lib/libc/locale ]
  # - [0x36AE34, data, lib/libkernl/klib]
  # - [0x36AE44, data, lib/libkernl/glue]
  # - [0x36AE4C, data, lib/libkernl/kprintf]
  # - [0x36AE54, data, lib/libkernl/sifrpc]
  - [ 0x36ae58, data, lib/libkernl/filestub ]
  # - [0x36AEEC, data, libkernl/eeloadfile]
  - [ 0x36aef8, data, lib/libkernl/initsys ]
  - [ 0x36af18, data, lib/libkernl/libosd ]
  - [ 0x36b6e0, data, lib/libkernl/alarm ]
  - [ 0x36be88, data, lib/libkernl/thread ]
  # - [0x36BE8C, data, lib/libkernl/sifcmd]
  - [ 0x36be90, data, lib/libkernl/tlbfunc ]
  # - [0x36C4DC, data, lib/libgcc/__main]
  - [ 0x36c4f0, data, lib/libgraph ]
  - [ 0x36c540, data, lib/libdma ]
  - [ 0x36c580, data, lib/libvu0 ]
  - [ 0x36c5b0, data, lib/libdbc ]
  - [ 0x36c5c0, data, lib/libdpad2 ]
  - [ 0x36c5f0, data, lib/libdvib ]
  - [ 0x36c600, data, lib/libcdvd ]
  - [ 0x36e070, data, lib/libpc ]
  - [ 0x36e080, data, lib/libmc ]
  - [ 0x36e0a0, data, lib/libipu ]
  - [ 0x36e120, data ]

  ## .rodata section ##
  - [ 0x38cc10, rodata ]
  - [ 0x38cf70, .rodata, worldfile ]
  - [ 0x38d008, rodata ]
  - [ 0x391b20, rodata, lib/libc/impure ]
  - [ 0x391b28, rodata, lib/libc/puts ]
  - [ 0x391b30, rodata, lib/libc/vfiprintf ]
  - [ 0x391d20, rodata, lib/libc/vfprintf ]
  - [ 0x391f30, rodata, lib/libc/dtoa ]
  - [ 0x391f88, rodata, lib/libc/locale ]
  - [ 0x391fd0, rodata, lib/libc/mprec ]
  - [ 0x392120, rodata, lib/libkernl/tty ]
  - [ 0x392170, rodata, lib/libkernl/kprintf ]
  - [ 0x3922d0, rodata, lib/libkernl/filestub ]
  - [ 0x392340, rodata, lib/libkernl/eeloadfile ]
  - [ 0x392350, rodata, lib/libkernl/iopreset ]
  - [ 0x392380, rodata, lib/libkernl/libosd ]
  - [ 0x392388, rodata, lib/libkernl/thread ]
  - [ 0x3923b0, rodata, lib/libkernl/tlbfunc ]
  - [ 0x392430, rodata, lib/libgcc/_divdi3 ]
  - [ 0x392530, rodata, lib/libgcc/_moddi3 ]
  - [ 0x392630, rodata, lib/libgcc/_udivdi3 ]
  - [ 0x392730, rodata, lib/libgcc/_umoddi3 ]
  - [ 0x392830, rodata, lib/libgcc/_thenan_df ]
  - [ 0x392850, rodata, lib/libgcc/frame-dwarf2 ]
  - [ 0x392920, rodata, lib/libgraph ]
  - [ 0x392e60, rodata, lib/libdma ]
  - [ 0x392ed0, rodata, lib/libdbc ]
  - [ 0x3930b8, rodata, lib/libpad2 ]
  - [ 0x3930e0, rodata, lib/libcdvd ]
  - [ 0x3932c8, rodata, lib/libm/s_atan ]
  - [ 0x393378, rodata, lib/libm/s_ceil ]
  - [ 0x393388, rodata, lib/libm/sf_cos ]
  - [ 0x393390, rodata, lib/libm/e_asin ]
  - [ 0x3934e0, rodata, lib/libm/e_atan2 ]
  - [ 0x393590, rodata, lib/libm/e_rem_pio2 ]
  - [ 0x3937e0, rodata, lib/libm/e_sqrt ]
  - [ 0x3937f0, rodata, lib/libm/ef_acos ]
  - [ 0x393828, rodata, lib/libm/ef_asin ]
  - [ 0x393880, rodata, lib/libm/ef_fmod ]
  - [ 0x393890, rodata, lib/libm/ef_pow ]
  - [ 0x393918, rodata, lib/libm/ef_rem_pio2 ]
  - [ 0x393cd8, rodata, lib/libm/ef_sqrt ]
  - [ 0x393ce0, rodata, lib/libm/k_cos ]
  - [ 0x393d48, rodata, lib/libm/k_rem_pio2 ]
  - [ 0x393db8, rodata, lib/libm/k_sin ]
  - [ 0x393e28, rodata, lib/libm/kf_cos ]
  - [ 0x393e48, rodata, lib/libm/kf_rem_pio2 ]
  # - [0x393E94, rodata, lib/libm/kf_sin]
  - [ 0x393eb0, rodata, lib/libm/kf_tan ]
  - [ 0x393ef8, rodata, lib/libm/s_floor ]
  - [ 0x393f08, rodata, lib/libm/s_scalbn ]
  - [ 0x393f38, rodata, lib/libm/sf_atan ]
  # - [0x393F8C, rodata, lib/libm/sf_floor]
  - [ 0x393f90, rodata, lib/libm/sf_scalbn ]
  - [ 0x393fa0, rodata, lib/libmc ]
  - [ 0x394028, rodata ]
- [ 0x394050 ]
