name: Kingdom Hearts (Final Mix)
sha1: e70bda789916142aafb53d85cef2e806b35ad8d8
options:
  basename: SLPS_251.98
  target_path: SLPS_251.98
  base_path: ..
  compiler: EEGCC
  find_file_boundaries: False
  platform: ps2
  create_undefined_funcs_auto: True
  undefined_funcs_auto_path: config/fm/undefined_funcs_auto.txt
  create_undefined_syms_auto: True
  undefined_syms_auto_path: config/fm/undefined_syms_auto.txt
  symbol_addrs_path: [config/fm/symbol_addrs.txt, config/fm/lib_symbol_addrs.txt]
  asm_path: asm
  src_path: src
  build_path: build/fm
  extensions_path: tools/splat_ext
  section_order: [".text", ".data", ".rodata", ".bss"]
  auto_link_sections: [".data", ".rodata", ".bss"]
  subalign: 8
  disasm_unknown: True
  named_regs_for_c_funcs: False
segments:
  - [0, databin, elf_header]
  - name: main
    type: code
    start: 0x80
    vram: 0x100000
    bss_size: 0x1E0F80
    subsegments:
    - [0x80, asm, crt0]
    - [0x258, asm]
    - [0x122F0, c, worldfile]
    - [0x12518, asm]

    - [0x14F398, asm, lib/libc/bsearch]
    - [0x14F468, asm, lib/libc/exit]
    - [0x14F518, asm, lib/libc/fiprintf]
    - [0x14F570, asm, lib/libc/malloc]
    - [0x14F610, asm, lib/libc/malloc_r]
    - [0x14FF90, asm, lib/libc/memcmp]
    # - [0x150024, asm, lib/libc/memcpy]
    # - [0x1500D4, asm, lib/libc/memset]
    - [0x150198, asm, lib/libc/mloc]
    - [0x150268, asm, lib/libc/printf]
    - [0x150338, asm, lib/libc/puts]
    - [0x1503E0, asm, lib/libc/qsort]
    - [0x150DD0, asm, lib/libc/rand]
    - [0x150E50, asm, lib/libc/sbrkr]
    - [0x150EA8, asm, lib/libc/sprintf]
    - [0x150FC0, asm, lib/libc/strcat]
    # - [0x1510EC, asm, lib/libc/strcmp]
    - [0x151230, asm, lib/libc/strcpy]
    # - [0x151344, asm, lib/libc/strlen]
    - [0x151480, asm, lib/libc/strncmp]
    - [0x151638, asm, lib/libc/vfiprintf]
    - [0x1523A8, asm, lib/libc/vfprintf]
    - [0x153E30, asm, lib/libc/vsprintf]
    - [0x153EE0, asm, lib/libc/wsetup]
    - [0x153FF0, asm, lib/libc/abort]
    - [0x154008, asm, lib/libc/dtoa]
    - [0x1554A0, asm, lib/libc/fflush]
    - [0x1555B8, asm, lib/libc/findfp]
    - [0x155858, asm, lib/libc/freer]
    - [0x155CC0, asm, lib/libc/fvwrite]
    - [0x1560A0, asm, lib/libc/fwalk]
    - [0x156138, asm, lib/libc/locale]
    - [0x156220, asm, lib/libc/makebuf]
    - [0x156378, asm, lib/libc/mbtowc_r]
    # - [0x1563AC, asm, lib/libc/memchr]
    # - [0x15648C, asm, lib/libc/memmove]
    - [0x156590, asm, lib/libc/mprec]
    - [0x1575A8, asm, lib/libc/s_isinf]
    - [0x1575F0, asm, lib/libc/s_isnan]
    - [0x157630, asm, lib/libc/signal]
    - [0x157918, asm, lib/libc/signalr]
    - [0x157990, asm, lib/libc/stdio]
    - [0x157B00, asm, lib/libc/writer]
    - [0x157B60, asm, lib/libc/callocr]
    - [0x157C18, asm, lib/libc/closer]
    - [0x157C70, asm, lib/libc/fstatr]
    - [0x157CD0, asm, lib/libc/lseekr]
    - [0x157D30, asm, lib/libc/readr]

    # lib/libkernl #
    - [0x157DC0, asm, lib/libkernl/klib]
    - [0x158660, asm, lib/libkernl/glue]
    - [0x158A30, asm, lib/libkernl/cache]
    - [0x158CB0, asm, lib/libkernl/intr]
    - [0x158EE0, asm, lib/libkernl/tty]
    - [0x159400, asm, lib/libkernl/kprintf]
    - [0x159DA0, asm, lib/libkernl/sifrpc]
    - [0x15AD00, asm, lib/libkernl/filestub]
    - [0x15E3A8, asm, lib/libkernl/eeloadfile]
    - [0x15F108, asm, lib/libkernl/iopreset]
    - [0x15F3B8, asm, lib/libkernl/diei]
    - [0x15F418, asm, lib/libkernl/initsys]
    - [0x15F680, asm, lib/libkernl/libosd]
    - [0x15FAA0, asm, lib/libkernl/alarm]
    - [0x15FBE0, asm, lib/libkernl/thread]
    - [0x15FF40, asm, lib/libkernl/deci2]
    - [0x160120, asm, lib/libkernl/sifcmd]
    - [0x160868, asm, lib/libkernl/tlbfunc]
    - [0x160D80, asm, lib/libkernl/tlbtrap]

    # lib/libgcc #
    - [0x1610E0, asm, lib/libgcc/_muldi3]
    - [0x161158, asm, lib/libgcc/_divdi3]
    - [0x1617F0, asm, lib/libgcc/_moddi3]
    - [0x161E80, asm, lib/libgcc/_udivdi3]
    - [0x162400, asm, lib/libgcc/_umoddi3]
    - [0x162968, asm, lib/libgcc/_fixunsdfdi]
    - [0x162A80, asm, lib/libgcc/_fixunssfdi]
    - [0x162BA8, asm, lib/libgcc/main]
    - [0x162D30, asm, lib/libgcc/_sf_to_df]
    - [0x162D70, asm, lib/libgcc/_addsub_df]
    - [0x163090, asm, lib/libgcc/_mul_df]
    - [0x163318, asm, lib/libgcc/_div_df]
    - [0x163458, asm, lib/libgcc/_compare_df]
    - [0x1634A8, asm, lib/libgcc/_si_to_df]
    - [0x163560, asm, lib/libgcc/_df_to_si]
    - [0x163600, asm, lib/libgcc/_make_df]
    - [0x163630, asm, lib/libgcc/_df_to_sf]
    - [0x163688, asm, lib/libgcc/_df_to_usi]
    - [0x163728, asm, lib/libgcc/frame-dwarf2]
    - [0x164CB8, asm, lib/libgcc/_floatdidf]
    - [0x164D60, asm, lib/libgcc/_unpack_sf]
    - [0x164DC0, asm, lib/libgcc/_make_sf]
    - [0x164DF0, asm, lib/libgcc/_pack_df]
    - [0x164EC8, asm, lib/libgcc/_unpack_df]
    - [0x164F88, asm, lib/libgcc/_fpcmp_parts_df]
    - [0x1650A8, asm, lib/libgcc/_pack_sf]
    - [0x165160, asm, lib/libgcc/atexit]
    - [0x165200, asm, lib/libgcc/errno]
    - [0x165210, asm, lib/libgcc/strncpy]

    - [0x1653D0, asm, lib/libgraph]
    - [0x166B30, asm, lib/libdma]
    - [0x167378, asm, lib/libvu0]
    - [0x1680C0, asm, lib/libdbc]
    - [0x168B20, asm, lib/libpad2]
    - [0x169378, asm, lib/libvib]
    - [0x1694E8, asm, lib/libcdvd]

    # lib/libm #
    - [0x16ADE0, asm, lib/libm/s_atan]
    - [0x16B2A8, asm, lib/libm/s_ceil]
    - [0x16B4B8, asm, lib/libm/s_cos]
    - [0x16B5E0, asm, lib/libm/s_fabs]
    - [0x16B618, asm, lib/libm/s_nan]
    - [0x16B640, asm, lib/libm/s_sin]
    - [0x16B778, asm, lib/libm/sf_cos]
    - [0x16B850, asm, lib/libm/sf_sin]
    - [0x16B938, asm, lib/libm/sf_tan]
    - [0x16B9B0, asm, lib/libm/w_asin]
    - [0x16B9C8, asm, lib/libm/w_atan2]
    - [0x16B9E0, asm, lib/libm/w_sqrt]
    - [0x16B9F8, asm, lib/libm/wf_acos]
    - [0x16BA10, asm, lib/libm/wf_asin]
    - [0x16BA28, asm, lib/libm/wf_atan2]
    - [0x16BA40, asm, lib/libm/wf_fmod]
    - [0x16BA58, asm, lib/libm/wf_pow]
    - [0x16BA70, asm, lib/libm/wf_sqrt]
    - [0x16BA88, asm, lib/libm/e_asin]
    - [0x16C0E0, asm, lib/libm/e_atan2]
    - [0x16C420, asm, lib/libm/e_rem_pio2]
    - [0x16C9D8, asm, lib/libm/e_sqrt]
    - [0x16CCF8, asm, lib/libm/ef_acos]
    - [0x16D120, asm, lib/libm/ef_asin]
    - [0x16D4C0, asm, lib/libm/ef_atan2]
    - [0x16D6A0, asm, lib/libm/ef_fmod]
    - [0x16D870, asm, lib/libm/ef_pow]
    - [0x16E050, asm, lib/libm/ef_rem_pio2]
    - [0x16E400, asm, lib/libm/ef_sqrt]
    - [0x16E4D0, asm, lib/libm/k_cos]
    - [0x16E7A8, asm, lib/libm/k_rem_pio2]
    - [0x16F2F8, asm, lib/libm/k_sin]
    - [0x16F530, asm, lib/libm/kf_cos]
    - [0x16F680, asm, lib/libm/kf_rem_pio2]
    - [0x16FEE8, asm, lib/libm/kf_sin]
    - [0x16FFF0, asm, lib/libm/kf_tan]
    - [0x170278, asm, lib/libm/s_floor]
    - [0x170490, asm, lib/libm/s_scalbn]
    - [0x170678, asm, lib/libm/sf_atan]
    - [0x170908, asm, lib/libm/sf_fabs]
    - [0x170930, asm, lib/libm/sf_floor]
    - [0x170A08, asm, lib/libm/sf_scalbn]
    - [0x170AD0, asm, lib/libm/s_copysign]
    - [0x170B18, asm, lib/libm/sf_copysign]

    - [0x170B58, asm, lib/libpc]
    - [0x170BE0, asm, lib/libmc]
    - [0x172448, asm, lib/libipu/libipu]
    - [0x1727B8, asm, lib/libipu/ipuinit]

## .data section ##
    - [0x172CF0, data]
    - [0x1BCCA8, .data, worldfile]
    - [0x1BCE20, data]
    - [0x36AEA8, data, lib/libc/mlock]
    - [0x36AEB0, data, lib/libc/locale]
    # - [0x36AEB4, data, lib/libkernl/klib]
    # - [0x36AEC4, data, lib/libkernl/glue]
    # - [0x36AECC, data, lib/libkernl/kprintf]
    # - [0x36AED4, data, lib/libkernl/sifrpc]
    - [0x36AED8, data, lib/libkernl/filestub]
    # - [0x36AF6C, data, libkernl/eeloadfile]
    - [0x36AF78, data, lib/libkernl/initsys]
    - [0x36AF98, data, lib/libkernl/libosd]
    - [0x36B760, data, lib/libkernl/alarm]
    - [0x36BF08, data, lib/libkernl/thread]
    # - [0x36BF0C, data, lib/libkernl/sifcmd]
    - [0x36BF10, data, lib/libkernl/tlbfunc]
    # - [0x36C55C, data, lib/libgcc/__main]
    - [0x36C570, data, lib/libgraph]
    - [0x36C5C0, data, lib/libdma]
    - [0x36C600, data, lib/libvu0]
    - [0x36C630, data, lib/libdbc]
    - [0x36C640, data, lib/libdpad2]
    - [0x36C670, data, lib/libdvib]
    - [0x36C680, data, lib/libcdvd]
    - [0x36E0F0, data, lib/libpc]
    - [0x36E100, data, lib/libmc]
    - [0x36E120, data, lib/libipu]
    - [0x36E1A0, data]

## .rodata section ##
    - [0x38CC90, rodata]
    - [0x38CFF0, .rodata, worldfile]
    - [0x38D088, rodata]
    - [0x391BA0, rodata, lib/libc/impure]
    - [0x391BA8, rodata, lib/libc/puts]
    - [0x391BB0, rodata, lib/libc/vfiprintf]
    - [0x391DA0, rodata, lib/libc/vfprintf]
    - [0x391FB0, rodata, lib/libc/dtoa]
    - [0x392008, rodata, lib/libc/locale]
    - [0x392050, rodata, lib/libc/mprec]
    - [0x3921A0, rodata, lib/libkernl/tty]
    - [0x3921F0, rodata, lib/libkernl/kprintf]
    - [0x392350, rodata, lib/libkernl/filestub]
    - [0x3923C0, rodata, lib/libkernl/eeloadfile]
    - [0x3923D0, rodata, lib/libkernl/iopreset]
    - [0x392400, rodata, lib/libkernl/libosd]
    - [0x392408, rodata, lib/libkernl/thread]
    - [0x392430, rodata, lib/libkernl/tlbfunc]
    - [0x3924B0, rodata, lib/libgcc/_divdi3]
    - [0x3925B0, rodata, lib/libgcc/_moddi3]
    - [0x3926B0, rodata, lib/libgcc/_udivdi3]
    - [0x3927B0, rodata, lib/libgcc/_umoddi3]
    - [0x3928B0, rodata, lib/libgcc/_thenan_df]
    - [0x3928D0, rodata, lib/libgcc/frame-dwarf2]
    - [0x3929A0, rodata, lib/libgraph]
    - [0x392EE0, rodata, lib/libdma]
    - [0x392F50, rodata, lib/libdbc]
    - [0x393138, rodata, lib/libpad2]
    - [0x393160, rodata, lib/libcdvd]
    - [0x393348, rodata, lib/libm/s_atan]
    - [0x3933F8, rodata, lib/libm/s_ceil]
    - [0x393408, rodata, lib/libm/sf_cos]
    - [0x393410, rodata, lib/libm/e_asin]
    - [0x393560, rodata, lib/libm/e_atan2]
    - [0x393610, rodata, lib/libm/e_rem_pio2]
    - [0x393860, rodata, lib/libm/e_sqrt]
    - [0x393870, rodata, lib/libm/ef_acos]
    - [0x3938A8, rodata, lib/libm/ef_asin]
    - [0x393900, rodata, lib/libm/ef_fmod]
    - [0x393910, rodata, lib/libm/ef_pow]
    - [0x393998, rodata, lib/libm/ef_rem_pio2]
    - [0x393D58, rodata, lib/libm/ef_sqrt]
    - [0x393D60, rodata, lib/libm/k_cos]
    - [0x393DC8, rodata, lib/libm/k_rem_pio2]
    - [0x393E38, rodata, lib/libm/k_sin]
    - [0x393EA8, rodata, lib/libm/kf_cos]
    - [0x393EC8, rodata, lib/libm/kf_rem_pio2]
    # - [0x393F14, rodata, lib/libm/kf_sin]
    - [0x393F30, rodata, lib/libm/kf_tan]
    - [0x393F78, rodata, lib/libm/s_floor]
    - [0x393F88, rodata, lib/libm/s_scalbn]
    - [0x393FB8, rodata, lib/libm/sf_atan]
    # - [0x39400C, rodata, lib/libm/sf_floor]
    - [0x394010, rodata, lib/libm/sf_scalbn]
    - [0x394020, rodata, lib/libmc]
    - [0x3940A8, rodata]
  - [0x394100, databin] # .reginfo / segment_1.2
  - [0x394118, databin]
  - [0x3A0CC8]
